export const AppConstants = {
  API_PREFIX: 'api/v1',
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  MAX_TRIBE_MEMBERS: 10,
  PET_NAME_MIN_LENGTH: 3,
  PET_NAME_MAX_LENGTH: 20,
  LEADERBOARD_SNAPSHOT_TTL_DAYS: 90,
} as const;
