/**
 * Catálogo centralizado de códigos de error.
 * Cada código es estable, orientado a máquina y único en todo el sistema.
 * OWASP: Nunca exponer detalles internos (stack, queries, tokens).
 */
export const ErrorCodes = {
  // ── General ──
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // ── Auth ──
  AUTH_INVALID_CODE: 'AUTH_INVALID_CODE',
  AUTH_EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_PROVIDER_UNAVAILABLE: 'AUTH_PROVIDER_UNAVAILABLE',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',

  // ── Users ──
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',

  // ── Pets ──
  PET_ALREADY_EXISTS: 'PET_ALREADY_EXISTS',
  PET_NOT_FOUND: 'PET_NOT_FOUND',
  PET_ITEM_NOT_FOUND: 'PET_ITEM_NOT_FOUND',
  PET_ITEM_NOT_OWNED: 'PET_ITEM_NOT_OWNED',
  PET_ITEM_ALREADY_UNLOCKED: 'PET_ITEM_ALREADY_UNLOCKED',
  PET_INSUFFICIENT_POINTS: 'PET_INSUFFICIENT_POINTS',

  // ── Tribes ──
  TRIBE_NOT_FOUND: 'TRIBE_NOT_FOUND',
  TRIBE_ALREADY_JOINED: 'TRIBE_ALREADY_JOINED',
  TRIBE_FULL_OR_RESTRICTED: 'TRIBE_FULL_OR_RESTRICTED',
  TRIBE_NOT_A_MEMBER: 'TRIBE_NOT_A_MEMBER',
  TRIBE_LEADER_CANNOT_LEAVE: 'TRIBE_LEADER_CANNOT_LEAVE',

  // ── Seasons ──
  SEASON_NOT_FOUND: 'SEASON_NOT_FOUND',
  SEASON_NOT_ACTIVE: 'SEASON_NOT_ACTIVE',
  SEASON_ALREADY_ACTIVE: 'SEASON_ALREADY_ACTIVE',

  // ── Challenges ──
  CHALLENGE_NOT_FOUND: 'CHALLENGE_NOT_FOUND',
  CHALLENGE_NOT_ACTIVE: 'CHALLENGE_NOT_ACTIVE',
  CHALLENGE_ALREADY_PLAYED: 'CHALLENGE_ALREADY_PLAYED',

  // ── Rewards ──
  REWARD_NOT_FOUND: 'REWARD_NOT_FOUND',
  REWARD_NOT_ELIGIBLE: 'REWARD_NOT_ELIGIBLE',
  REWARD_ALREADY_CLAIMED: 'REWARD_ALREADY_CLAIMED',

  // ── Payments ──
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_DUPLICATE: 'PAYMENT_DUPLICATE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
